Repository hendrikmaus/helm-templexer, pull requests merged in 2021-08, with the labels that each got.

#54 Fix `cargo clippy` Validate Checks
  src/config.rs
Labels: internal

#55 Use caching in CI
  .github/workflows/ci.yaml
Labels: internal

#53 Extend release workflow with crates.io publishing
  .github/workflows/release.yaml
Labels: internal

#58 Add minimal configuration for release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
Labels: internal

#64 Delete Makefile
  Makefile
Labels: internal

#56 Use colored help output and global versioning
  src/main.rs
Labels: enhancement

#67 Add an additional cache key, stable over multiple jobs
  .github/workflows/release.yaml
Labels: internal

#63 Revert "Allow writing to stdout using `helm-templexer render --stdout <config>` (#45)"
  README.md
  src/config.rs
  src/main.rs
  src/render_cmd.rs
  tests/data/gen_cfg.sh
  tests/data/nginx-chart/Chart.yaml
  tests/data/nginx-chart/values/edge.yaml
  tests/data/nginx-chart/values/next-edge.yaml
  tests/data/nginx-chart/values/prod-eu-w4.yaml
  tests/data/nginx-chart/values/prod.yaml
  tests/data/nginx-chart/values/stage.yaml
  tests/data/test-stdout
  tests/data/test-stdout-bin
  tests/test_render.rs
Labels: breaking-change

#59 Reorganize integration tests
  tests/integration/main.rs
  tests/integration/render.rs
  tests/integration/validate.rs
Labels: internal

#60 Add option to update helm dependencies
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/render_cmd.rs
Labels: enhancement

#57 Bump to version 1
  Cargo.lock
  Cargo.toml
  docs/v1.md
Labels: internal

#72 Implement `format_serde_error`
  Cargo.lock
  Cargo.toml
  README.md
  src/config.rs
  src/main.rs
  tests/data/config_chart_does_not_exist.toml
  tests/data/config_chart_does_not_exist.yaml
  tests/data/config_example.json
  tests/data/config_example.toml
  tests/data/config_invalid.yaml
  tests/data/config_invalid0.toml
  tests/data/gen_cfg.sh
  tests/integration/render.rs
  tests/integration/validate.rs
Labels: enhancement

#76 Update rust-build action and add darwin support
  .github/workflows/release.yaml
Labels: internal

#79 Update CODEOWNERS
  CODEOWNERS
Labels: internal

#80 Add `--update-dependencies` to readme
  README.md
Labels: documentation
