Repository hendrikmaus/helm-templexer, pull requests merged in 2021-09, with the labels that each got.

#84 Pipe Output Through A Tool
  Cargo.lock
  Cargo.toml
  README.md
  src/main.rs
  src/render_cmd.rs
  tests/integration/render.rs
Labels: enhancement

#83 Explicitly manage the working directory to support multiple input files
  .github/workflows/release.yaml
  src/config.rs
  src/render_cmd.rs
  src/validate_cmd.rs
  tests/integration/render.rs
Labels: bug

#85 Remove unused dependencies
  Cargo.lock
  Cargo.toml
Labels: internal

#88 Use latest version of rust-build.action
  .github/workflows/release.yaml
Labels: internal

#92 Add crates.io badge to README
  README.md
Labels: documentation
