Repository hendrikmaus/helm-templexer, pull requests merged in 2022-12, with the labels that each got.

#99 chore: fix builds and asset uploads in GitHub Actions
  .github/workflows/ci.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
  src/render_cmd.rs
Labels: enhancement, internal

#100 chore: simplify the dev container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/provision.sh
Labels: internal

#104 chore: move to release-please
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
Labels: internal

#103 chore: print stdout and stderr on failure if not empty
  src/render_cmd.rs
  tests/data/config_invalid_helm_option.yaml
  tests/integration/render.rs
Labels: enhancement

#106 fix(cd): re-enable `cross` in containerise job
  .github/workflows/release.yaml
Labels: bug, internal

#108 fix(cd): pass release upload url to binary build job
  .github/workflows/release.yaml
Labels: bug, internal

#109 fix(cd): include tag name in the release artifacts
  .github/workflows/release.yaml
Labels: bug, internal

#111 fix(cd): use gha expressions instead of env var
  .github/workflows/release.yaml
Labels: bug, internal

#113 fix(cd): generate and upload checksum files for release artifacts
  .github/workflows/release.yaml
Labels: bug, internal

#115 docs: update binary checksum verification example
  README.md
Labels: documentation
